# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups:
- website_sale_checkout_country_vat
- website_sale_vat_required
repo_description: Modules aiming to support e-commerce specific needs. This includes
    all the new website_sale related modules.
repo_name: Odoo E-Commerce Modules
repo_slug: e-commerce
repo_website: https://github.com/OCA/e-commerce
travis_apt_packages: []
travis_apt_sources: []

