# Copyright 2017 LasLabs Inc.
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Affiliate Program",
    "summary": "This module allows creation of affiliates and "
               "tracking the sales conversions generated by them.",
    "version": "12.0.1.0.0",
    "category": "Website",
    "website": "https://github.com/OCA/e-commerce",
    "author": "LasLabs, Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "depends": [
        "website_sale",
    ],
    "data": [
        "data/sale_affiliate_data.xml",
        "security/ir.model.access.csv",
        "views/sale_affiliate_view.xml",
        "views/sale_affiliate_request_view.xml",
        "views/sale_order_view.xml",
    ],
    "demo": [
        "demo/sale_affiliate_demo.xml",
    ],
    "installable": True,
}
