[project]
name = "odoo-addons-oca-e-commerce"
version = "18.0.20260318.0"
dependencies = [
    "odoo-addon-product_template_multi_link==18.0.*",
    "odoo-addon-product_template_multi_link_date_span==18.0.*",
    "odoo-addon-product_variant_multi_link==18.0.*",
    "odoo-addon-website_sale_acquirer_confirm_order==18.0.*",
    "odoo-addon-website_sale_attribute_filter_form_submit==18.0.*",
    "odoo-addon-website_sale_b2x_alt_price==18.0.*",
    "odoo-addon-website_sale_barcode_search==18.0.*",
    "odoo-addon-website_sale_cart_expire==18.0.*",
    "odoo-addon-website_sale_category_breadcrumb==18.0.*",
    "odoo-addon-website_sale_checkout_country_vat==18.0.*",
    "odoo-addon-website_sale_checkout_skip_payment==18.0.*",
    "odoo-addon-website_sale_comparison_hide_price==18.0.*",
    "odoo-addon-website_sale_hide_empty_category==18.0.*",
    "odoo-addon-website_sale_hide_price==18.0.*",
    "odoo-addon-website_sale_order_shipping_modification==18.0.*",
    "odoo-addon-website_sale_order_type==18.0.*",
    "odoo-addon-website_sale_product_attribute_filter_category==18.0.*",
    "odoo-addon-website_sale_product_attribute_value_filter_existing==18.0.*",
    "odoo-addon-website_sale_product_brand==18.0.*",
    "odoo-addon-website_sale_product_detail_attribute_image==18.0.*",
    "odoo-addon-website_sale_product_item_cart_custom_qty==18.0.*",
    "odoo-addon-website_sale_product_reference_displayed==18.0.*",
    "odoo-addon-website_sale_product_sort==18.0.*",
    "odoo-addon-website_sale_require_legal==18.0.*",
    "odoo-addon-website_sale_secondary_unit==18.0.*",
    "odoo-addon-website_sale_stock_available==18.0.*",
    "odoo-addon-website_sale_stock_list_preview==18.0.*",
    "odoo-addon-website_sale_stock_provisioning_date==18.0.*",
    "odoo-addon-website_sale_suggest_create_account==18.0.*",
    "odoo-addon-website_sale_tax_toggle==18.0.*",
    "odoo-addon-website_sale_vat_required==18.0.*",
    "odoo-addon-website_sale_wishlist_hide_price==18.0.*",
    "odoo-addon-website_sale_wishlist_keep==18.0.*",
    "odoo-addon-website_snippet_product_category==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
