[project]
name = "odoo-addons-oca-e-commerce"
version = "19.0.20260604.2"
dependencies = [
    "odoo-addon-website_sale_cart_expire==19.0.*",
    "odoo-addon-website_sale_checkout_skip_payment==19.0.*",
    "odoo-addon-website_sale_product_brand==19.0.*",
    "odoo-addon-website_sale_product_reference_displayed==19.0.*",
    "odoo-addon-website_sale_stock_picking_policy==19.0.*",
    "odoo-addon-website_sale_stock_provisioning_date==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
