[project]
name = "odoo-addons-oca-e-commerce"
version = "19.0.20260810.4"
dependencies = [
    "odoo-addon-product_template_multi_link==19.0.*",
    "odoo-addon-product_variant_multi_link==19.0.*",
    "odoo-addon-website_sale_acquirer_confirm_order==19.0.*",
    "odoo-addon-website_sale_barcode_search==19.0.*",
    "odoo-addon-website_sale_cart_expire==19.0.*",
    "odoo-addon-website_sale_charge_payment_fee==19.0.*",
    "odoo-addon-website_sale_checkout_skip_payment==19.0.*",
    "odoo-addon-website_sale_hide_price==19.0.*",
    "odoo-addon-website_sale_one_time_delivery_address==19.0.*",
    "odoo-addon-website_sale_order_type==19.0.*",
    "odoo-addon-website_sale_product_accessory==19.0.*",
    "odoo-addon-website_sale_product_attribute_value_filter_existing==19.0.*",
    "odoo-addon-website_sale_product_brand==19.0.*",
    "odoo-addon-website_sale_product_detail_attribute_image==19.0.*",
    "odoo-addon-website_sale_product_item_cart_custom_qty==19.0.*",
    "odoo-addon-website_sale_product_minimal_price==19.0.*",
    "odoo-addon-website_sale_product_reference_displayed==19.0.*",
    "odoo-addon-website_sale_product_sort==19.0.*",
    "odoo-addon-website_sale_quick_checkout==19.0.*",
    "odoo-addon-website_sale_require_legal==19.0.*",
    "odoo-addon-website_sale_stock_available==19.0.*",
    "odoo-addon-website_sale_stock_list_preview==19.0.*",
    "odoo-addon-website_sale_stock_picking_policy==19.0.*",
    "odoo-addon-website_sale_stock_provisioning_date==19.0.*",
    "odoo-addon-website_sale_tax_selection==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
