import setuptools

with open('VERSION.txt', 'r') as f:
    version = f.read().strip()

setuptools.setup(
    name="odoo13-addons-oca-e-commerce",
    description="Meta package for oca-e-commerce Odoo addons",
    version=version,
    install_requires=[
        'odoo13-addon-product_template_multi_link',
        'odoo13-addon-product_template_multi_link_date_span',
        'odoo13-addon-product_variant_multi_link',
        'odoo13-addon-website_account_fiscal_position_partner_type',
        'odoo13-addon-website_sale_attribute_filter_category',
        'odoo13-addon-website_sale_attribute_filter_form_submit',
        'odoo13-addon-website_sale_attribute_filter_order',
        'odoo13-addon-website_sale_attribute_filter_price',
        'odoo13-addon-website_sale_b2x_alt_price',
        'odoo13-addon-website_sale_cart_expire',
        'odoo13-addon-website_sale_cart_no_redirect',
        'odoo13-addon-website_sale_category_breadcrumb',
        'odoo13-addon-website_sale_checkout_country_vat',
        'odoo13-addon-website_sale_checkout_skip_payment',
        'odoo13-addon-website_sale_comparison_hide_price',
        'odoo13-addon-website_sale_free_qty',
        'odoo13-addon-website_sale_google_tag_manager',
        'odoo13-addon-website_sale_hide_empty_category',
        'odoo13-addon-website_sale_hide_price',
        'odoo13-addon-website_sale_invoice_address',
        'odoo13-addon-website_sale_order_type',
        'odoo13-addon-website_sale_product_attachment',
        'odoo13-addon-website_sale_product_attribute_filter_visibility',
        'odoo13-addon-website_sale_product_attribute_value_filter_existing',
        'odoo13-addon-website_sale_product_brand',
        'odoo13-addon-website_sale_product_description',
        'odoo13-addon-website_sale_product_detail_attribute_image',
        'odoo13-addon-website_sale_product_detail_attribute_value_image',
        'odoo13-addon-website_sale_product_item_cart_custom_qty',
        'odoo13-addon-website_sale_product_minimal_price',
        'odoo13-addon-website_sale_product_reference_displayed',
        'odoo13-addon-website_sale_product_sort',
        'odoo13-addon-website_sale_product_style_badge',
        'odoo13-addon-website_sale_require_legal',
        'odoo13-addon-website_sale_require_login',
        'odoo13-addon-website_sale_resource_booking',
        'odoo13-addon-website_sale_secondary_unit',
        'odoo13-addon-website_sale_stock_available',
        'odoo13-addon-website_sale_stock_available_display',
        'odoo13-addon-website_sale_stock_force_block',
        'odoo13-addon-website_sale_stock_list_preview',
        'odoo13-addon-website_sale_stock_provisioning_date',
        'odoo13-addon-website_sale_suggest_create_account',
        'odoo13-addon-website_sale_tax_toggle',
        'odoo13-addon-website_sale_vat_required',
        'odoo13-addon-website_sale_wishlist_keep',
        'odoo13-addon-website_snippet_carousel_product',
        'odoo13-addon-website_snippet_product_category',
    ],
    classifiers=[
        'Programming Language :: Python',
        'Framework :: Odoo',
        'Framework :: Odoo :: 13.0',
    ]
)
